### ISSUE TITLE
Kodi 19 Support 

### ISSUE THREAD

**Issue by jaredcat** [rmrector/script.playrandomvideos#6]
Any plans to support python 3 for Kodi 19?

**Comment by rmrector** [comment]
Give [2.0.0 a try](https://github.com/rmrector/repository.rector.stuff/tree/python3/script.playrandomvideos). I'll submit it to the official repo after some testing.

**Comment by atreyuhere** [comment]
Tried v v2.0.0 (2021-01-29) -- first tests are positive. Glad to see this one back, thanks!

**Comment by jaredcat** [comment]
Seems to be working on 19.0-RC1 (2021-01-15) on my nvidia shield here

**Comment by rmrector** [comment]
v2 just merged into the official Kodi Matrix repo. Cheers.
